#!/bin/sh

dnf install -y akregator
dnf install -y arianna
dnf install -y arj
dnf install -y arp-scan
dnf install -y audacious
dnf install -y bat
dnf install -y bleachbit
dnf install -y btop
dnf install -y calibre
dnf install -y dmenu
dnf install -y dolphin
dnf install -y dracut
dnf install -y dunst
dnf install -y duplicity
dnf install -y exa
dnf install -y exif
dnf install -y feh
dnf install -y ffmpeg
dnf install -y ffmpeg-devel
dnf install -y flameshot
dnf install -y flowblade
dnf install -y foliate
dnf install -y fzf
dnf install -y ghostwriter
dnf install -y git
dnf install -y git-core
dnf install -y gparted
dnf install -y GraphicsMagick
dnf install -y handbrake
dnf install -y i3
dnf install -y i3blocks
dnf install -y i3lock
dnf install -y i3status
dnf install -y ImageMagick
dnf install -y inkscape
dnf install -y kalendar
dnf install -y kasts
dnf install -y kate
dnf install -y kate-plugins
dnf install -y kbackup
dnf install -y kdenlive
dnf install -y kdiff3
dnf install -y keepassxc
dnf install -y kget
dnf install -y kile
dnf install -y klavaro
dnf install -y kompare
dnf install -y krename
dnf install -y krusader
dnf install -y ksnip
dnf install -y ksysguard
dnf install -y ktextaddons
dnf install -y ktorrent
dnf install -y ktouch
dnf install -y kwave
dnf install -y l3afpad
dnf install -y libreoffice
dnf install -y libXres-devel
dnf install -y lm_sensors
dnf install -y lm_sensors-devel
dnf install -y lxappearance
dnf install -y lynx
dnf install -y materia-gtk-theme
dnf install -y meld
dnf install -y micro
dnf install -y mousepad
dnf install -y mpv
dnf install -y mupdf
dnf install -y neovim
dnf install -y netcat
dnf install -y newsboat
dnf install -y nitrogen
dnf install -y nmap
dnf install -y numlockx
dnf install -y obs
dnf install -y odt2txt
dnf install -y p7zip
dnf install -y pandoc
dnf install -y picom
dnf install -y plasma-firewall
dnf install -y plasmatube
dnf install -y qbittorrent
dnf install -y qmmp
dnf install -y qt5ct
dnf install -y ranger
dnf install -y ripgrep
dnf install -y rofi
dnf install -y scrot
dnf install -y slick-greeter
dnf install -y sxiv
dnf install -y thermald
dnf install -y thunar
dnf install -y timeshift
dnf install -y tldr
dnf install -y tlp
dnf install -y tlp-rdw
dnf install -y tmux
dnf install -y tokodon
dnf install -y ulauncher
dnf install -y unzip
dnf install -y vlc
dnf install -y w3m
dnf install -y w3m-img
dnf install -y wireshark
dnf install -y xautolock
dnf install -y xbacklight
dnf install -y xpdf
dnf install -y xrandr
dnf install -y xterm
dnf install -y yakuake
dnf install -y youtube-dl
dnf install -y yt-dlp
dnf install -y zathura
dnf install -y zathura-fish-completion
dnf install -y zathura-pdf-mupdf
dnf install -y zathura-plugins-all
